"""mark column added in score 

Revision ID: 16d38dc04048
Revises: 55685afac634
Create Date: 2024-12-03 15:15:21.780678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d38dc04048'
down_revision: Union[str, None] = '55685afac634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('mark', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'mark')
    # ### end Alembic commands ###
