"""Message describing the migration

Revision ID: 1a151f54eae5
Revises: 8c914cd2c403
Create Date: 2024-12-13 10:05:38.611915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a151f54eae5'
down_revision: Union[str, None] = '8c914cd2c403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=mysql.TINYINT(),
               comment='1->active,2->inactive,-1->delete',
               existing_comment='1->active,2->inactive,0->delete',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=mysql.TINYINT(),
               comment='1->active,2->inactive,0->delete',
               existing_comment='1->active,2->inactive,-1->delete',
               existing_nullable=True)
    # ### end Alembic commands ###
