"""add new column in taskdetails

Revision ID: 1c20abf1f255
Revises: 51d02cccced0
Create Date: 2024-12-07 17:05:01.251759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c20abf1f255'
down_revision: Union[str, None] = '51d02cccced0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_detail', sa.Column('mentor_time', sa.Time(), nullable=True))
    op.alter_column('task_detail', 'expected_time',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Time(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_detail', 'expected_time',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('task_detail', 'mentor_time')
    # ### end Alembic commands ###
