"""make change in user model add batch and course id column and comment batch_course_details

Revision ID: 277334e5c5de
Revises: 8926daf90cb9
Create Date: 2024-11-28 12:29:46.778473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '277334e5c5de'
down_revision: Union[str, None] = '8926daf90cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_batch_course_details_id', table_name='batch_course_details')
    op.drop_table('batch_course_details')
    op.add_column('user', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'user', 'batch', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'course_id')
    op.drop_column('user', 'batch_id')
    op.create_table('batch_course_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-> active 2 -> inactive'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trainer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name='batch_course_details_ibfk_1'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='batch_course_details_ibfk_2'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='batch_course_details_ibfk_3'),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], name='batch_course_details_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_batch_course_details_id', 'batch_course_details', ['id'], unique=False)
    # ### end Alembic commands ###
