"""Message describing the migration

Revision ID: 28e37f233317
Revises: 16d38dc04048
Create Date: 2024-12-04 10:08:00.233385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '28e37f233317'
down_revision: Union[str, None] = '16d38dc04048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_history', sa.Column('Ispaused', mysql.TINYINT(), nullable=True, comment='1-> yes 2 -> no'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_history', 'Ispaused')
    # ### end Alembic commands ###
