"""student_exam_details model added

Revision ID: 297c90aea60a
Revises: f45e699d79bb
Create Date: 2024-12-17 10:52:08.695735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297c90aea60a'
down_revision: Union[str, None] = 'f45e699d79bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer')
    # ### end Alembic commands ###
