"""Message describing the migration

Revision ID: 33ff27f98d0e
Revises: 28e37f233317
Create Date: 2024-12-04 10:42:40.498946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ff27f98d0e'
down_revision: Union[str, None] = '28e37f233317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'work_history', 'task_detail', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_history', type_='foreignkey')
    # ### end Alembic commands ###
