"""Message describing the migration

Revision ID: 381a3455bb43
Revises: a391427ad81e
Create Date: 2024-12-03 14:51:38.730384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '381a3455bb43'
down_revision: Union[str, None] = 'a391427ad81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_detail', 'expected_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_detail', sa.Column('expected_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
