"""add foreign key in course material

Revision ID: 4827d4e59392
Revises: 79898bcbb18e
Create Date: 2024-11-28 17:48:15.779968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4827d4e59392'
down_revision: Union[str, None] = '79898bcbb18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_material', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_material', 'user', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_material', type_='foreignkey')
    op.drop_column('course_material', 'created_by_user_id')
    # ### end Alembic commands ###
