"""Message describing the migration

Revision ID: 51d02cccced0
Revises: fd0db8268b16
Create Date: 2024-12-05 15:21:00.120138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d02cccced0'
down_revision: Union[str, None] = 'fd0db8268b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_detail', sa.Column('task', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_detail', 'task')
    # ### end Alembic commands ###
