"""Message describing the migration

Revision ID: 5ee62ea6a630
Revises: fca26fbfd10b
Create Date: 2024-12-10 09:50:29.320703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ee62ea6a630'
down_revision: Union[str, None] = 'fca26fbfd10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('image', sa.String(length=255), nullable=True))
    op.drop_column('course', 'resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('resume', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('course', 'image')
    # ### end Alembic commands ###
