"""Message describing the migration

Revision ID: 6c3cdea1b42c
Revises: 39233c9e7a04
Create Date: 2024-12-17 14:23:41.848764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c3cdea1b42c'
down_revision: Union[str, None] = '39233c9e7a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_informarion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StudentExamDetail_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1-> active , 2-> inactive'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['StudentExamDetail_id'], ['student_exam_detail.id'], ),
    sa.ForeignKeyConstraint(['answer_id'], ['option.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_informarion_id'), 'exam_informarion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_informarion_id'), table_name='exam_informarion')
    op.drop_table('exam_informarion')
    # ### end Alembic commands ###
