"""add new column in score model

Revision ID: 6f767a679dff
Revises: 5ee62ea6a630
Create Date: 2024-12-10 14:02:13.356938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f767a679dff'
down_revision: Union[str, None] = '5ee62ea6a630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('student_project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'score', 'student_project_detail', ['student_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'student_project_id')
    # ### end Alembic commands ###
