"""course_material.py and coursemedia.py model created

Revision ID: 79898bcbb18e
Revises: 277334e5c5de
Create Date: 2024-11-28 17:20:21.189126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79898bcbb18e'
down_revision: Union[str, None] = '277334e5c5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1-> active 2 -> inactive'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_material_id'), 'course_material', ['id'], unique=False)
    op.create_table('course_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1-> active 2 -> inactive'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('course_material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_material_id'], ['course_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_media_id'), 'course_media', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_media_id'), table_name='course_media')
    op.drop_table('course_media')
    op.drop_index(op.f('ix_course_material_id'), table_name='course_material')
    op.drop_table('course_material')
    # ### end Alembic commands ###
