"""Message describing the migration

Revision ID: 7a19553c9d07
Revises: f3f3f64409f8
Create Date: 2024-11-29 10:26:24.941155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a19553c9d07'
down_revision: Union[str, None] = 'f3f3f64409f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_history', sa.Column('breakEnd_time', sa.DateTime(), nullable=True))
    op.add_column('work_history', sa.Column('workEnd_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_work_report_id'), 'work_report', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_report_id'), table_name='work_report')
    op.drop_column('work_history', 'workEnd_time')
    op.drop_column('work_history', 'breakEnd_time')
    # ### end Alembic commands ###
