"""Message describing the migration

Revision ID: 823e649ca8c8
Revises: e441a9027835
Create Date: 2024-12-13 09:30:29.677442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '823e649ca8c8'
down_revision: Union[str, None] = 'e441a9027835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('checkIn_status', mysql.TINYINT(), nullable=True, comment='1-> chek_in 2 -> check_out'))
    op.drop_column('attendance', 'work_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('work_status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-> chek_in 2 -> check_out'))
    op.drop_column('attendance', 'checkIn_status')
    # ### end Alembic commands ###
