"""add type id in studentexamdetails

Revision ID: 865535057718
Revises: f7ba8084c788
Create Date: 2024-12-17 11:36:00.055151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865535057718'
down_revision: Union[str, None] = 'f7ba8084c788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_exam_detail', sa.Column('type__id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_exam_detail_type__id'), 'student_exam_detail', ['type__id'], unique=False)
    op.create_foreign_key(None, 'student_exam_detail', 'type_of_question', ['type__id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_exam_detail', type_='foreignkey')
    op.drop_index(op.f('ix_student_exam_detail_type__id'), table_name='student_exam_detail')
    op.drop_column('student_exam_detail', 'type__id')
    # ### end Alembic commands ###
