"""rename the column in user table

Revision ID: 8926daf90cb9
Revises: c1dfd9635690
Create Date: 2024-11-27 16:46:57.688829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8926daf90cb9'
down_revision: Union[str, None] = 'c1dfd9635690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,2->inactive,0->delete'))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->active,2->inactive,0->delete'))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
