"""in batch,course,task add new column and relationship

Revision ID: 93f493907cd2
Revises: ca9f7b09155a
Create Date: 2024-12-04 17:32:41.976498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f493907cd2'
down_revision: Union[str, None] = 'ca9f7b09155a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('from_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(length=250), nullable=True))
    op.add_column('task', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'task', 'batch', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'batch_id')
    op.drop_column('task', 'course_id')
    op.drop_column('task', 'description')
    op.drop_column('task', 'end_date')
    op.drop_column('task', 'from_date')
    # ### end Alembic commands ###
