"""Message describing the migration

Revision ID: 957472144873
Revises: 7f74334eecaa
Create Date: 2024-11-29 17:57:20.518703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957472144873'
down_revision: Union[str, None] = '7f74334eecaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_detail', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_detail', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_detail', type_='foreignkey')
    op.drop_column('task_detail', 'user_id')
    # ### end Alembic commands ###
