"""added CourseMaterial

Revision ID: 980b93c2bb90
Revises: 9c6f9fe3747d
Create Date: 2024-12-28 14:50:24.742385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '980b93c2bb90'
down_revision: Union[str, None] = '9c6f9fe3747d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'image')
    op.drop_column('course', 'color2')
    op.drop_column('course', 'color1')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'course', ['course_id'], ['id'])
    op.add_column('course', sa.Column('color1', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('course', sa.Column('color2', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('course', sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
