"""Message describing the migration

Revision ID: 9badc069ff8f
Revises: 88a615ac55b5
Create Date: 2024-12-03 14:37:14.371933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9badc069ff8f'
down_revision: Union[str, None] = '88a615ac55b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_detail', 'priority',
               existing_type=mysql.TINYINT(),
               comment='1-> High 2 -> medium 3 -> low',
               existing_comment='1-> High 2 -> medium 3 -> ow',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_detail', 'priority',
               existing_type=mysql.TINYINT(),
               comment='1-> High 2 -> medium 3 -> ow',
               existing_comment='1-> High 2 -> medium 3 -> low',
               existing_nullable=True)
    # ### end Alembic commands ###
