"""deleted examinformation model

Revision ID: aa79b4eddf2f
Revises: 6c3cdea1b42c
Create Date: 2024-12-17 17:05:25.648143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa79b4eddf2f'
down_revision: Union[str, None] = '6c3cdea1b42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exam_informarion_id', table_name='exam_informarion')
    op.drop_table('exam_informarion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_informarion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('StudentExamDetail_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-> active , 2-> inactive'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['StudentExamDetail_id'], ['student_exam_detail.id'], name='exam_informarion_ibfk_1'),
    sa.ForeignKeyConstraint(['answer_id'], ['option.id'], name='exam_informarion_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_exam_informarion_id', 'exam_informarion', ['id'], unique=False)
    # ### end Alembic commands ###
