"""Message describing the migration

Revision ID: af4b6ff4218c
Revises: 33ff27f98d0e
Create Date: 2024-12-04 10:43:50.122727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af4b6ff4218c'
down_revision: Union[str, None] = '33ff27f98d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_history', sa.Column('taskDetail_id', sa.Integer(), nullable=True))
    op.drop_constraint('work_history_ibfk_2', 'work_history', type_='foreignkey')
    op.create_foreign_key(None, 'work_history', 'task_detail', ['taskDetail_id'], ['id'])
    op.drop_column('work_history', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_history', sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'work_history', type_='foreignkey')
    op.create_foreign_key('work_history_ibfk_2', 'work_history', 'task_detail', ['task_id'], ['id'])
    op.drop_column('work_history', 'taskDetail_id')
    # ### end Alembic commands ###
