"""Message describing the migration

Revision ID: b31d8712b01b
Revises: e9eeef68f7a1
Create Date: 2024-12-05 09:46:03.723147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b31d8712b01b'
down_revision: Union[str, None] = 'e9eeef68f7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_detail', sa.Column('close_status', mysql.TINYINT(), nullable=True, comment='1-> close '))
    op.alter_column('task_detail', 'complete_status',
               existing_type=mysql.TINYINT(),
               comment='1-> complete  ',
               existing_comment='1-> complete 2 -> not complete',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_detail', 'complete_status',
               existing_type=mysql.TINYINT(),
               comment='1-> complete 2 -> not complete',
               existing_comment='1-> complete  ',
               existing_nullable=True)
    op.drop_column('task_detail', 'close_status')
    # ### end Alembic commands ###
