"""Message describing the migration

Revision ID: ba58d8f87671
Revises: 957472144873
Create Date: 2024-11-30 16:57:51.866736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba58d8f87671'
down_revision: Union[str, None] = '957472144873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_detail_id', table_name='task_detail')
    op.drop_table('task_detail')
    op.drop_index('ix_attendance_id', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_work_history_id', table_name='work_history')
    op.drop_table('work_history')
    op.drop_table('work_report')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_report',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('check_in', mysql.DATETIME(), nullable=True),
    sa.Column('check_out', mysql.DATETIME(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('work_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('break_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('in_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('out_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('in_latitude', mysql.DECIMAL(precision=15, scale=7), nullable=True),
    sa.Column('in_longitude', mysql.DECIMAL(precision=15, scale=7), nullable=True),
    sa.Column('out_latitude', mysql.DECIMAL(precision=15, scale=7), nullable=True),
    sa.Column('out_longitude', mysql.DECIMAL(precision=15, scale=7), nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-> active 2 -> inactive'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='work_report_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='work_report_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('work_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_report_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('break_time', mysql.DATETIME(), nullable=True),
    sa.Column('work_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-> active 2 -> inactive'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('breakEnd_time', mysql.DATETIME(), nullable=True),
    sa.Column('workEnd_time', mysql.DATETIME(), nullable=True),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='work_history_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_work_history_id', 'work_history', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('check_in', mysql.DATETIME(), nullable=True),
    sa.Column('check_out', mysql.DATETIME(), nullable=True),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('work_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('break_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('in_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('out_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('in_latitude', mysql.DECIMAL(precision=15, scale=7), nullable=True),
    sa.Column('in_longitude', mysql.DECIMAL(precision=15, scale=7), nullable=True),
    sa.Column('out_latitude', mysql.DECIMAL(precision=15, scale=7), nullable=True),
    sa.Column('out_longitude', mysql.DECIMAL(precision=15, scale=7), nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-> active 2 -> inactive'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='attendance_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='attendance_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_attendance_id', 'attendance', ['id'], unique=False)
    op.create_table('task_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_report_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-> active 2 -> inactive'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='task_detail_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='task_detail_ibfk_3'),
    sa.ForeignKeyConstraint(['work_report_id'], ['work_report.id'], name='task_detail_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_task_detail_id', 'task_detail', ['id'], unique=False)
    # ### end Alembic commands ###
