"""Message describing the migration

Revision ID: bfd131ab3742
Revises: 40904384b043
Create Date: 2024-12-13 11:41:54.038098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfd131ab3742'
down_revision: Union[str, None] = '40904384b043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_report', 'taken_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_report', sa.Column('taken_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
