"""add new column in taskdetails model

Revision ID: ca9f7b09155a
Revises: 5884e4aa9282
Create Date: 2024-12-04 15:21:13.326497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9f7b09155a'
down_revision: Union[str, None] = '5884e4aa9282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_detail', sa.Column('task_description', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_detail', 'task_description')
    # ### end Alembic commands ###
