"""Message describing the migration

Revision ID: e022188fc09d
Revises: 381a3455bb43
Create Date: 2024-12-03 14:52:14.830988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e022188fc09d'
down_revision: Union[str, None] = '381a3455bb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_detail', sa.Column('expected_time', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_detail', 'expected_time')
    # ### end Alembic commands ###
