"""Message describing the migration

Revision ID: e407c8de1a5f
Revises: 6cbecea307ef
Create Date: 2024-11-29 15:12:06.973227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e407c8de1a5f'
down_revision: Union[str, None] = '6cbecea307ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_history', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work_history', 'task', ['task_id'], ['id'])
    op.add_column('work_report', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work_report', 'task', ['task_id'], ['id'])
    op.drop_column('work_report', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_report', sa.Column('task', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'work_report', type_='foreignkey')
    op.drop_column('work_report', 'task_id')
    op.drop_constraint(None, 'work_history', type_='foreignkey')
    op.drop_column('work_history', 'task_id')
    # ### end Alembic commands ###
