"""passoutyear model created

Revision ID: e441a9027835
Revises: 6f767a679dff
Create Date: 2024-12-11 16:44:48.738862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e441a9027835'
down_revision: Union[str, None] = '6f767a679dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordyear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordyear_id'), 'passwordyear', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passwordyear_id'), table_name='passwordyear')
    op.drop_table('passwordyear')
    # ### end Alembic commands ###
