"""task_report_url column added in task model

Revision ID: e9eeef68f7a1
Revises: 93f493907cd2
Create Date: 2024-12-04 17:36:24.459078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9eeef68f7a1'
down_revision: Union[str, None] = '93f493907cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_report_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_report_url')
    # ### end Alembic commands ###
