"""make change in Applicationdetails model (field passed_out_year datetime to string)

Revision ID: ed6677cd8af1
Revises: a3baea590bba
Create Date: 2024-11-26 18:02:34.918109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed6677cd8af1'
down_revision: Union[str, None] = 'a3baea590bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'passed_out_year',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_details', 'passed_out_year',
               existing_type=sa.String(length=4),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
