"""Message describing the migration

Revision ID: fca26fbfd10b
Revises: 1c20abf1f255
Create Date: 2024-12-10 09:48:32.331719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca26fbfd10b'
down_revision: Union[str, None] = '1c20abf1f255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('resume', sa.String(length=255), nullable=True))
    op.add_column('course', sa.Column('color1', sa.String(length=255), nullable=True))
    op.add_column('course', sa.Column('color2', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'color2')
    op.drop_column('course', 'color1')
    op.drop_column('course', 'resume')
    # ### end Alembic commands ###
