"""Message describing the migration

Revision ID: fd0db8268b16
Revises: b31d8712b01b
Create Date: 2024-12-05 15:13:38.864719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd0db8268b16'
down_revision: Union[str, None] = 'b31d8712b01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_material', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_material', 'batch', ['batch_id'], ['id'])
    op.add_column('task_detail', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.add_column('task_detail', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_constraint('task_detail_ibfk_2', 'task_detail', type_='foreignkey')
    op.create_foreign_key(None, 'task_detail', 'user', ['trainer_id'], ['id'])
    op.drop_column('task_detail', 'task_id')
    op.drop_column('task_detail', 'task_description')
    op.drop_column('task_detail', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_detail', sa.Column('priority', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-> High 2 -> medium 3 -> low'))
    op.add_column('task_detail', sa.Column('task_description', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('task_detail', sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_detail', type_='foreignkey')
    op.create_foreign_key('task_detail_ibfk_2', 'task_detail', 'task', ['task_id'], ['id'])
    op.drop_column('task_detail', 'rating')
    op.drop_column('task_detail', 'trainer_id')
    op.drop_constraint(None, 'course_material', type_='foreignkey')
    op.drop_column('course_material', 'batch_id')
    # ### end Alembic commands ###
